namespace ForgeDeck.Core.Scanning;

public sealed record InstallHint(string Pattern, string Label);

public sealed record KnownTool(
    string Name, ToolType Type, string Logo, string? ResumeArgs,
    string[] ExeNames, InstallHint[] Hints);

public static class KnownTools
{
    public static readonly IReadOnlyList<KnownTool> All = new KnownTool[]
    {
        new("Claude Code", ToolType.Cli, "C/", "--continue",
            new[] { "claude" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.claude\local", "用户目录") }),
        new("Codex CLI", ToolType.Cli, "CX", null,
            new[] { "codex" },
            new[] { new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录"),
                    new InstallHint(@"%APPDATA%\npm", "npm 全局") }),
        new("Gemini CLI", ToolType.Cli, "G", "--resume",
            new[] { "gemini" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局") }),
        new("Grok Build", ToolType.Cli, "GB", "--continue",
            new[] { "grok" },
            new[] { new InstallHint(@"%USERPROFILE%\.grok\bin", "用户目录") }),
        new("OpenCode", ToolType.Cli, "OC", "--continue",
            new[] { "opencode" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.opencode\bin", "用户目录"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("GitHub Copilot CLI", ToolType.Cli, "GH", "--continue",
            new[] { "copilot" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%LOCALAPPDATA%\GitHubCopilotCLI", "用户目录") }),
        new("Qwen Code", ToolType.Cli, "Qw", "--continue",
            new[] { "qwen" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.qwen\bin", "用户目录"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Goose", ToolType.Cli, "Go", null,
            new[] { "goose" },
            new[] { new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Amp", ToolType.Cli, "Am", null,
            new[] { "amp" },
            new[] { new InstallHint(@"%USERPROFILE%\.amp\bin", "用户目录"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Crush", ToolType.Cli, "Cr", null,
            new[] { "crush" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Continue CLI", ToolType.Cli, "Cn", "--resume",
            new[] { "cn" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Kiro CLI", ToolType.Cli, "Ki", null,
            new[] { "kiro-cli" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Kiro CLI", "用户目录"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("iFlow CLI", ToolType.Cli, "iF", null,
            new[] { "iflow" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局") }),
        new("Factory Droid", ToolType.Cli, "Dr", null,
            new[] { "droid" },
            new[] { new InstallHint(@"%USERPROFILE%\.factory\bin", "用户目录"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录"),
                    new InstallHint(@"%APPDATA%\npm", "npm 全局") }),
        new("Cline", ToolType.Cli, "Cl", null,
            new[] { "cline" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Kimi Code", ToolType.Cli, "Km", null,
            new[] { "kimi" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.kimi\bin", "用户目录"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Lingma", ToolType.Cli, "Lm", null,
            new[] { "lingma" },
            new[] { new InstallHint(@"%USERPROFILE%\.lingma\bin", "用户目录"),
                    new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("CodeBuddy", ToolType.Cli, "CB", null,
            new[] { "codebuddy" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Augment", ToolType.Cli, "Au", null,
            new[] { "auggie" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Qoder", ToolType.Cli, "Qo", null,
            new[] { "qoder" },
            new[] { new InstallHint(@"%USERPROFILE%\.qoder\bin", "用户目录"),
                    new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("MiniMax", ToolType.Cli, "Mx", null,
            new[] { "minimax" },
            new[] { new InstallHint(@"%APPDATA%\npm", "npm 全局"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Ollama", ToolType.Cli, "Ol", null,
            new[] { "ollama" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Ollama", "用户目录"),
                    new InstallHint(@"%USERPROFILE%\.local\bin", "用户目录") }),
        new("Aider", ToolType.Cli, "Ai", null,
            new[] { "aider" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Python\Scripts", "Python Scripts"),
                    new InstallHint(@"%APPDATA%\Python\Scripts", "Python Scripts") }),
        new("Cursor", ToolType.Gui, "Cu", null,
            new[] { "Cursor" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Cursor", "用户目录") }),
        new("Cursor Agent", ToolType.Cli, "Cu", null,
            new[] { "cursor-agent" },
            new[] { new InstallHint(@"%PROGRAMFILES%\Cursor\resources\app\bin", "开始菜单") }),
        new("Windsurf", ToolType.Gui, "W", null,
            new[] { "Windsurf" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Windsurf", "用户目录") }),
        new("Trae", ToolType.Gui, "T", null,
            new[] { "Trae" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Trae", "用户目录") }),
        new("Zed", ToolType.Gui, "Z", null,
            new[] { "zed", "Zed" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Zed", "用户目录") }),
        new("VS Code", ToolType.Gui, "VS", null,
            new[] { "Code" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Microsoft VS Code", "用户目录"),
                    new InstallHint(@"%PROGRAMFILES%\Microsoft VS Code", "用户目录") }),
        new("Warp", ToolType.Gui, "Wp", null,
            new[] { "Warp" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\Warp", "用户目录") }),
        new("ChatGPT", ToolType.Gui, "CG", null,
            new[] { "ChatGPT" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\ChatGPT", "用户目录"),
                    new InstallHint(@"%LOCALAPPDATA%\OpenAI", "用户目录") }),
        new("LM Studio", ToolType.Gui, "LM", null,
            new[] { "LM Studio" },
            new[] { new InstallHint(@"%LOCALAPPDATA%\Programs\LM Studio", "用户目录"),
                    new InstallHint(@"%USERPROFILE%\.lmstudio", "用户目录") }),
    };

    public static KnownTool? MatchByExeName(string fileName)
    {
        var name = Path.GetFileNameWithoutExtension(fileName);
        return All.FirstOrDefault(t =>
            t.ExeNames.Any(n => string.Equals(n, name, StringComparison.OrdinalIgnoreCase)));
    }

    public static KnownTool? MatchByName(string displayName) =>
        All.Where(t => displayName.Contains(t.Name, StringComparison.OrdinalIgnoreCase))
          .OrderByDescending(t => t.Name.Length)
          .FirstOrDefault();
}
